language: node_js
cache: npm
node_js:
- node
before_install:
- cd server
install:
- npm install
script:
- npm test
env:
  global:
    - SESSION_SECRET=$SESSION_SECRET
    - DB_URI=$DB_URI
    - DB_URI_TEST=$DB_URI_TEST
